# config/packages/vich_uploader.yaml

vich_uploader:
    db_driver: orm
    mappings:
        your_mapping_name:
            uri_prefix:         '/images/products'
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: vich_uploader.namer_origname
